// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb // import "./"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestUserList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUserList) Reset()         { *m = RequestUserList{} }
func (m *RequestUserList) String() string { return proto.CompactTextString(m) }
func (*RequestUserList) ProtoMessage()    {}
func (*RequestUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1c371e3ce3aaf7d6, []int{0}
}
func (m *RequestUserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUserList.Unmarshal(m, b)
}
func (m *RequestUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUserList.Marshal(b, m, deterministic)
}
func (dst *RequestUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUserList.Merge(dst, src)
}
func (m *RequestUserList) XXX_Size() int {
	return xxx_messageInfo_RequestUserList.Size(m)
}
func (m *RequestUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUserList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUserList proto.InternalMessageInfo

type RequestCheckToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCheckToken) Reset()         { *m = RequestCheckToken{} }
func (m *RequestCheckToken) String() string { return proto.CompactTextString(m) }
func (*RequestCheckToken) ProtoMessage()    {}
func (*RequestCheckToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1c371e3ce3aaf7d6, []int{1}
}
func (m *RequestCheckToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCheckToken.Unmarshal(m, b)
}
func (m *RequestCheckToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCheckToken.Marshal(b, m, deterministic)
}
func (dst *RequestCheckToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCheckToken.Merge(dst, src)
}
func (m *RequestCheckToken) XXX_Size() int {
	return xxx_messageInfo_RequestCheckToken.Size(m)
}
func (m *RequestCheckToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCheckToken.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCheckToken proto.InternalMessageInfo

func (m *RequestCheckToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReplyUserList struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyUserList) Reset()         { *m = ReplyUserList{} }
func (m *ReplyUserList) String() string { return proto.CompactTextString(m) }
func (*ReplyUserList) ProtoMessage()    {}
func (*ReplyUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1c371e3ce3aaf7d6, []int{2}
}
func (m *ReplyUserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserList.Unmarshal(m, b)
}
func (m *ReplyUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserList.Marshal(b, m, deterministic)
}
func (dst *ReplyUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserList.Merge(dst, src)
}
func (m *ReplyUserList) XXX_Size() int {
	return xxx_messageInfo_ReplyUserList.Size(m)
}
func (m *ReplyUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserList proto.InternalMessageInfo

func (m *ReplyUserList) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Introduction         string   `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Roles                []string `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	Token                string   `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1c371e3ce3aaf7d6, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestUserList)(nil), "proto.RequestUserList")
	proto.RegisterType((*RequestCheckToken)(nil), "proto.RequestCheckToken")
	proto.RegisterType((*ReplyUserList)(nil), "proto.ReplyUserList")
	proto.RegisterType((*User)(nil), "proto.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterUserClient is the client API for GreeterUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterUserClient interface {
	GetUserList(ctx context.Context, in *RequestUserList, opts ...grpc.CallOption) (*ReplyUserList, error)
	CheckToken(ctx context.Context, in *RequestCheckToken, opts ...grpc.CallOption) (*User, error)
}

type greeterUserClient struct {
	cc *grpc.ClientConn
}

func NewGreeterUserClient(cc *grpc.ClientConn) GreeterUserClient {
	return &greeterUserClient{cc}
}

func (c *greeterUserClient) GetUserList(ctx context.Context, in *RequestUserList, opts ...grpc.CallOption) (*ReplyUserList, error) {
	out := new(ReplyUserList)
	err := c.cc.Invoke(ctx, "/proto.GreeterUser/GetUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterUserClient) CheckToken(ctx context.Context, in *RequestCheckToken, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.GreeterUser/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterUserServer is the server API for GreeterUser service.
type GreeterUserServer interface {
	GetUserList(context.Context, *RequestUserList) (*ReplyUserList, error)
	CheckToken(context.Context, *RequestCheckToken) (*User, error)
}

func RegisterGreeterUserServer(s *grpc.Server, srv GreeterUserServer) {
	s.RegisterService(&_GreeterUser_serviceDesc, srv)
}

func _GreeterUser_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUserList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterUserServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GreeterUser/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterUserServer).GetUserList(ctx, req.(*RequestUserList))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterUser_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCheckToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterUserServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GreeterUser/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterUserServer).CheckToken(ctx, req.(*RequestCheckToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GreeterUser",
	HandlerType: (*GreeterUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserList",
			Handler:    _GreeterUser_GetUserList_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _GreeterUser_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_1c371e3ce3aaf7d6) }

var fileDescriptor_user_1c371e3ce3aaf7d6 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xbf, 0xed, 0x3b, 0x79, 0x55, 0x3a, 0x94, 0xb2, 0xe4, 0x14, 0xf6, 0x62, 0xbd,
	0x44, 0xa8, 0x08, 0x82, 0x78, 0xd1, 0x43, 0x2f, 0x9e, 0x82, 0x5e, 0xbc, 0xa5, 0xcd, 0x80, 0xa1,
	0x35, 0x1b, 0x77, 0x37, 0x8a, 0x67, 0xbf, 0x9d, 0x9f, 0x4a, 0x76, 0x93, 0xa6, 0xa9, 0xa7, 0xce,
	0xf3, 0x7b, 0x3a, 0x1b, 0xe6, 0x07, 0xd0, 0x28, 0x92, 0x69, 0x2d, 0x85, 0x16, 0x18, 0xd8, 0x1f,
	0x3e, 0x85, 0xb3, 0x8c, 0xde, 0x1b, 0x52, 0xfa, 0x59, 0x91, 0x7c, 0x2c, 0x95, 0xe6, 0x17, 0x30,
	0xed, 0xd0, 0xc3, 0x2b, 0x6d, 0xb6, 0x4f, 0x62, 0x4b, 0x15, 0xce, 0x20, 0xd0, 0x66, 0x60, 0x4e,
	0xe2, 0x2c, 0xfe, 0x65, 0x6d, 0xe0, 0x37, 0x70, 0x92, 0x51, 0xbd, 0xfb, 0xda, 0xef, 0xe2, 0x39,
	0x4c, 0x9a, 0x6e, 0x66, 0x4e, 0xe2, 0x2d, 0xa2, 0x65, 0xd4, 0x7e, 0x2f, 0x35, 0x7f, 0xc9, 0xfa,
	0x92, 0xff, 0x38, 0xe0, 0x1b, 0x84, 0xa7, 0xe0, 0x96, 0x45, 0xf7, 0xaa, 0x5b, 0x16, 0x18, 0xb7,
	0x2f, 0x54, 0xf9, 0x1b, 0x31, 0xd7, 0xd2, 0x3e, 0x9b, 0xae, 0xce, 0x95, 0xfa, 0x14, 0xb2, 0x60,
	0x5e, 0xdb, 0xed, 0x33, 0x22, 0xf8, 0x76, 0xc7, 0xb7, 0xdc, 0xce, 0x38, 0x87, 0x30, 0xff, 0xc8,
	0x75, 0x2e, 0x59, 0x60, 0x69, 0x97, 0x90, 0xc3, 0xff, 0xb2, 0xd2, 0x52, 0x14, 0xcd, 0x46, 0x97,
	0xa2, 0x62, 0xa1, 0x6d, 0x8f, 0x98, 0x39, 0x58, 0x8a, 0x1d, 0x29, 0x36, 0x4e, 0x3c, 0x73, 0xb0,
	0x0d, 0x07, 0x0d, 0x93, 0x81, 0x86, 0xe5, 0xb7, 0x03, 0xd1, 0x4a, 0x12, 0x69, 0x92, 0xf6, 0xa6,
	0x3b, 0x88, 0x56, 0xd4, 0x0b, 0xc5, 0x79, 0xa7, 0xe0, 0x8f, 0xe8, 0x78, 0xd6, 0xf3, 0x81, 0x42,
	0x3e, 0xc2, 0x6b, 0x80, 0x81, 0x79, 0x76, 0xbc, 0x7d, 0x68, 0xe2, 0xa1, 0x5a, 0x3e, 0xba, 0x1f,
	0xbf, 0x04, 0xe9, 0xe5, 0x6d, 0xbd, 0x5e, 0x87, 0x16, 0x5f, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0xda, 0x94, 0x2d, 0xef, 0x01, 0x00, 0x00,
}
